ttrssdb:
  image: nornagon/postgres
  ports:
    - "5432:5432"
  volumes:
    - /srv/docker/ttrss/mnt:/mnt
  mem_limit: 512M
ttrss:
  image: otsuka512/docker-ttrss
  links:
    - ttrssdb:db
  ports:
    - "8083:80"
  mem_limit: 512M
  restart: always
